In [1]:
import pandas as pd
pd.__version__

'1.5.3'

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [3]:
len(data)

2160

In [4]:
len(data.Brand.unique())

27

In [5]:
data.isnull().any()

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

In [6]:
data[data['Brand']=='Dell'].groupby('Model').agg({'Final Price':'max'})

Final Price
Model                 
Latitude       2450.71
Precision      3936.00
Vostro         1895.48
XPS            3012.09

In [7]:
data.Screen.median()

15.6

In [8]:
data.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [9]:
data['screen']=data.Screen.fillna(15.6)

In [10]:
data.Screen.median()

15.6

In [11]:
data.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [12]:
Innjoo=data[data['Brand']=='Innjoo']

In [15]:
Innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  \
1478  Intel Celeron    8      256          SSD  NaN    15.6    No   
1479  Intel Celeron    8      512          SSD  NaN    15.6    No   
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No   
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No   
1482  Intel Celeron    6      128          SSD  NaN    14.1    No   
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No   

      Final Price  screen  
1478       311.37    15.6  
1479       392.55    15.6  
1480       251.40    14.1  
1481       383.61    14.1  
1482       317.02    14.1  
1483       431.38    14.1

In [13]:
X=Innjoo[['RAM','Storage','screen']]

In [16]:
import numpy as np 
X=np.array(X)

In [19]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [20]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [21]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [24]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [29]:
XTX=matrix_matrix_multiplication(X.T,X)

In [30]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [31]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [27]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])

In [32]:
K=matrix_matrix_multiplication(XTX_inv,X.T)

In [33]:
K

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [35]:
w=K*y

In [36]:
w.sum()

91.29988062995487